### ISSUE TITLE
Set up Docker Skeleton (Linux fuse) resembles

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#17]
1. As a Developer
2. I request the Software developers to create a docker skeleton 
3. So that this docker file skeleton can be used to quickly get the GitHub docker project started.

**Comment by vaidehi-for-coding** [comment]
Everyone who is done with this task please comment done.

**Comment by DOMEscho** [comment]
done
