### ISSUE TITLE
Update Dockerfile and docker-compose running 

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#30]
## User story
1. As a Developer
2. I want a Docker Compose implemented for the project
3. So that we can build and run the project easily

## Acceptance criteria
*  Docker compose starts the container with all the existing features working

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included into the release (candidate)
    7. Code Coverage:
         60 % - for Features
         70 % - for Sprint Release
         80 % - for Product Release

**Comment by CharineeSrikhaolan** [comment]
docker-compose.yml works. Linter problem sticks.
