### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by tuhinmallick** [amosproj/amos-ss2021-synthetic-file-system#4]
## User story
1. As a Team Member
2. I want  the roles to be assigned week by week
3. So that a plan and history of role assignments so that everyone knows their job

## Acceptance criteria
* The project should be planned at the start of the
* More roles can be assigned beyond the four required ones
* ...

## Definition of done
* Added only after week 5
* The same for all features

**Comment by tuhinmallick** [comment]
Please comment Okay, if you agree with the role assignment.

**Comment by ma-schulze** [comment]
Okey

**Comment by CharineeSrikhaolan** [comment]
that's ok for me

**Comment by finleymercyabraham** [comment]
Okay..

**Comment by MarlonWe** [comment]
OKAY

**Comment by tuhinmallick** [comment]
Okay

**Comment by DOMEscho** [comment]
okay for me

**Comment by sandraaocode** [comment]
Okay for me.

**Comment by vaidehi-for-coding** [comment]
ok
