### ISSUE TITLE
Restructure the README text file

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#41]
## User story
1. As a software developer
2. I want the README files to contain instructions and additional help, and details about updates.
3. So that the README files describe what kind of project it is, how it can be useful, how to install and use it.

## Acceptance criteria
* Team members understand very clear the whole project without having to look at the source code.

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included into the release (candidate)
    7. Code Coverage:
         60 % - for Features
         70 % - for Sprint Release
         80 % - for Product Release

**Comment by sandraaocode** [comment]
[Synthetic File System Build and Deployment Documentation.pdf](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6541133/Synthetic.File.System.Build.and.Deployment.Documentation.pdf)
[Synthetic File System Technical Documentation.pdf](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6541134/Synthetic.File.System.Technical.Documentation.pdf)
[Synthetic File System User Documentation.pdf](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6541136/Synthetic.File.System.User.Documentation.pdf)

**Comment by CharineeSrikhaolan** [comment]
@sandraaocode Could you please also highlight where I can improve(not comprehensible or grammatically incorrect)?
