### ISSUE TITLE
Metadata Hub

### ISSUE THREAD

**Issue by tuhinmallick** [amosproj/amos-ss2021-synthetic-file-system#5]
## User story
1. As a Project Member
2. I need to go through the information of Metadata Hub
3. So that I can understand the underlying infrastructure of the project

## Acceptance criteria
* The information is well laid out in form of Presentation, Flyers and overview

**Comment by tuhinmallick** [comment]
Please go through this feature

**Comment by vaidehi-for-coding** [comment]
Done

**Comment by MarlonWe** [comment]
Done

**Comment by CharineeSrikhaolan** [comment]
Done

**Comment by CharineeSrikhaolan** [comment]
Done

**Comment by sandraaocode** [comment]
Done.

**Comment by ma-schulze** [comment]
Done

**Comment by finleymercyabraham** [comment]
Done.

**Comment by DOMEscho** [comment]
Done

**Comment by tuhinmallick** [comment]
Done
