### ISSUE TITLE
Implement WRITE support for SFS

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#52]
## Problems to solve:  
Currently we are not able to WRITE files through the virtual file system
## Further details:
we want to be able to create new files which leads to the update of the underlying interface (e.g - metadata hub)
## Proposals:
Implement the WRITE functionality of currently available backends and make them accessible with the FUSE.

## Acceptance criteria
* Be able to write files to virtual file system and by that the underlying file structure.
* Create UNIT tests 

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included into the release (candidate)
    7. Code Coverage:
         60 % - for Features
         70 % - for Sprint Release
         80 % - for Product Release

**Comment by CharineeSrikhaolan** [comment]
[test_write_mdh_py.txt](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6697358/test_write_mdh_py.txt)


I have tried to write the testcase according to last version of write support(without caching), but with no success.

**Comment by CharineeSrikhaolan** [comment]
see test_write_mdh.py in branch 63-64-mdh_cache
