### ISSUE TITLE
Make the building of the file tree modular

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#54]
## Problems to solve:
The current SFS mirrors the existing file structure of the backend (like most other virtual file systems e.g - Curl FTPFS).

## Further details:
It should be possible to plug-in a custom algorithm that displays the file structure differently. 
The problem of unique path will come up.

## Proposals:
Abstract the file path into an identifier and use them as path. 
Include semantic encoding to the path.

## Acceptance criteria
- Clear API to add a tree-build algorithm.
- Example algorithm of a flat tree 

* ...

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included into the release (candidate)
    7. Code Coverage:
         60 % - for Features
         70 % - for Sprint Release
         80 % - for Product Release

**Comment by tuhinmallick** [comment]
Create another task for Unit testing
