### ISSUE TITLE
Construct an user interface for controlling the filtering process

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#60]
[##](![UI](https://user-images.githubusercontent.com/74312631/122190743-c4fafa80-ce9a-11eb-8fdd-a5c3bff611ff.jpeg)) Problems to solve:
Create a user-friendly UI with which you can apply filters for specific partners.

## Further details:
* For example a partner could be -- > mdh-core-1 or mdh-core-2
* Check the attached image for illustrative detail

## Proposals:
Provides an option to select the following: 
1. Partners can be selected
2. An algorithm can be selected 
3. Filters can be added or deleted, each filter consists of 
            - a) dropdown for metadata criteria 
            - b) dropdown for a conditional statement 
            - c) a text field (or whatever relates to the criteria or nothing) for specific filtering
4. Run button to run the applied filter (only) for that partner
## Acceptance criteria
The filtering mechanism is working properly

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included in the release (candidate)
    7. Code Coverage:
         40 % - for Features
         50 % - for Sprint Release
         60 % - for Product Release

**Comment by finleymercyabraham** [comment]
![UI](https://user-images.githubusercontent.com/74312631/122191120-1c996600-ce9b-11eb-92fe-ccf569e23e50.jpeg)

**Comment by MarlonWe** [comment]
![sfs_gui](https://user-images.githubusercontent.com/31160135/123949323-ba645900-d9a2-11eb-952e-6b526467cf6a.png)
