### ISSUE TITLE
Research and familiarise with a video-making tool

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#61]
## Problems to solve:
Create an informative and presentable video for the demo day.

## Further details:
* Compare multiple video-making tools and select one that meets our project needs.

## Proposals:
* Research a video-making tool with good recording quality and sufficient functionalities and familiarise yourself with it.

## Acceptance criteria
* A test video for the demo day is successfully created and plays without any problems

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included in the release (candidate)
    7. Code Coverage:
         40 % - for Features
         50 % - for Sprint Release
         60 % - for Product Release

**Comment by CharineeSrikhaolan** [comment]
https://user-images.githubusercontent.com/82507823/122991485-5f7ca180-d3a5-11eb-82d6-22583970bebd.mp4

**Comment by CharineeSrikhaolan** [comment]
[Software_VDO_making.docx](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6697269/Software_VDO_making.docx)

**Comment by sandraaocode** [comment]
Helped Charinee: I researched and compared multiple video creation tools and decided on PowerPoint for our project, because I believe it has a good recording quality, nice built-in features and we are all quite acquainted with it.
