### ISSUE TITLE
Clone Client Repository

### ISSUE THREAD

**Issue by tuhinmallick** [amosproj/amos-ss2021-synthetic-file-system#7]
## User story
1. As a Team Member
2. I want the SDs to clone the client repo: https://github.com/amos-project2/metadata-hub
3. So that before the next sprint, everyone has the requisite knowledge of the project.

## Acceptance criteria
* The repo should be cloned as required.

## Definition of done
* Complete before next sprint (Wednesday 21.04)

**Comment by DOMEscho** [comment]
Please let me know within the comments if you were able to successfully clone the repo.
If you encounter any problems or don't know what to do feel free to contact me.

**Comment by CharineeSrikhaolan** [comment]
![Screenshot 2021-04-24 at 15 20 06](https://user-images.githubusercontent.com/82507823/115960253-99016f80-a510-11eb-9a7e-d00698e5e687.png)
I did clone the repo :)

**Comment by vaidehi-for-coding** [comment]
Done with cloning.

**Comment by ma-schulze** [comment]
Done

**Comment by MarlonWe** [comment]
Done

**Comment by sandraaocode** [comment]
Done.
